# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsdlove', '0002_auto_20180902_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=100, verbose_name='链接序号')),
                ('link_name', models.CharField(max_length=100, verbose_name='链接名字')),
                ('link_address', models.CharField(max_length=100, verbose_name='链接地址')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
    ]
