# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zsdlove', '0004_public_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='public_notice',
            options={'verbose_name': '站点公告', 'verbose_name_plural': '站点公告'},
        ),
        migrations.AlterField(
            model_name='public_notice',
            name='notice_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 16, 10, 13, 493238, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
